version: "3.9"
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: pyatform-api
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=pyatform;Username=postgres;Password=postgres"
      AzureBlob__Key: "${AzureBlob__Key}"
      AzureBlob__ConnectionString: "${AzureBlob__ConnectionString}"
      AzureBlob__ContainerName: "${AzureBlob__ContainerName}"
    ports:
      - "8080:8080"
    networks:
      - pyatform-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp

  db:
    image: postgres:16
    container_name: pyatform-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pyatform
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # this maps /top_users_function.sql to docker-entrypoint-initdb.d from which postgres will autoexecute it
      - ./Misc/top_users_function.sql:/docker-entrypoint-initdb.d/top_users_function.sql
    ports:
      - "5432:5432"
    networks:
      - pyatform-net
  pgadmin:
    image: dpage/pgadmin4
    container_name: pyatform-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.admin
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    networks:
      - pyatform-net

volumes:
  postgres_data:

networks:
  pyatform-net:
